# This release does not include the full source to Python. This file is here to
# prevent the Unununium bulid system from attempting to configue Python.
# Although the Python used in Unununium is nearly unmodified, some creative
# hacks were required to get it to build. The full source to the changes are
# available at http://unununium.org/download
